name: Deploy master branch on AWS EB
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Generate deployment package
      run: zip -r miracle-bot-v${{ steps.vars.outputs.sha_short }}.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: miracle-bot
        environment_name: Miraclebot-env
        version_label: ${{ steps.vars.outputs.sha_short }}
        region: eu-central-1
        deployment_package: miracle-bot-v${{ steps.vars.outputs.sha_short }}.zip